reconciliation/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reconciliation_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reconciliation_app/urls.py
from django.urls import path
from .views import *

app_name = 'rc_app'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('', reconciliation_page, name='reconciliation_page'),
]

reconciliation_app/models.py
from django.db import models


class ProductCategory(models.Model):
    """ Категория товаров """
    name = models.CharField(
        max_length=50,
        verbose_name='название категории',
        unique=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория товара'
        verbose_name_plural = 'категории товаров'
        ordering = ['name']


class Product(models.Model):
    """ Товар """
    name = models.CharField(
        max_length=100,
        verbose_name='товар',
        unique=True,
        db_index=True,
    )
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория товара',
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ['name']


class ReconciliationDate(models.Model):
    """ Дата сверки """
    date = models.DateField(
        verbose_name='дата сверки',
        blank=True,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='товар',
        null=True,
    )

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = 'дата сверки'
        verbose_name_plural = 'даты сверки'
        ordering = ['product']

reconciliation_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    """ Вход пользователя """
    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'input-login'}),
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'input-login'}),
    )

reconciliation_app/views.py
import datetime

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import LoginForm
from .models import ProductCategory, Product, ReconciliationDate


class LoginUserView(LoginView):
    """ Логин """
    form_class = LoginForm
    template_name = 'reconciliation_app/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вход'
        return context

    def get_success_url(self):
        return reverse_lazy('rc_app:reconciliation_page')


@login_required(login_url='rc_app:login_view')
def logout_view(request):
    """ Выход """
    logout(request)
    return redirect('rc_app:login_view')


@login_required(login_url='rc_app:login_view')
def reconciliation_page(request):
    """ Страница сверки с датами сверки """
    categories = ProductCategory.objects.all()
    if request.method == 'POST':
        cleaned_data = request.POST.copy()
        del cleaned_data['csrfmiddlewaretoken']
        for p in cleaned_data:
            if cleaned_data[p]:
                # Получаем список всех дат сверки конкретного продукта
                # и сравниваем их с переданной датой. Повторяющиеся даты не записываем
                dates = [d.date for d in ReconciliationDate.objects.filter(product=int(p))]
                date = datetime.datetime.strptime(cleaned_data[p], "%Y-%m-%d").date()
                if date not in dates:
                    ReconciliationDate.objects.create(
                        date=date,
                        product=Product.objects.get(pk=int(p))
                    )
        return redirect('rc_app:reconciliation_page')
    context = {'title': 'Сверка', 'categories': categories}
    return render(request, 'reconciliation_app/reconciliation_page.html', context)

reconciliation_app/templates/reconciliation_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'reconciliation_app/css/common.css' %}">
    <link rel="shortcut icon" href="{% static 'reconciliation_app/favicon.ico' %}">
    {% block styles %}
    {% endblock styles %}
</head>
<body>
{% block content %}
{% endblock content %}
{% block js %}
{% endblock js %}
</body>
</html>

reconciliation_app/templates/reconciliation_app/login.html
{% extends 'reconciliation_app/base.html' %}

{% block content %}
<div class="wrapper">
    <form action="" method="post" class="login-form">
        {{ form.non_field_errors }}
        <div class="login-input-container">
            {% csrf_token %}
            <label for="{{ form.username.id_for_label }}" class="label-login">Имя пользователя</label>
            {{ form.username }}
            <label for="{{ form.password.id_for_label }}" class="label-login">Пароль</label>
            {{ form.password }}    
        </div>
        <button type="submit" class="login-btn">Войти</button>
    </form>
</div>
{% endblock content %}

reconciliation_app/templates/reconciliation_app/reconciliation_page.html
{% extends 'reconciliation_app/base.html' %}
{% load latest_date %}
{% load static %}

{% block content %}
<div class="wrapper wrapper-rec">
    <header class="header" id="head">
        <div class="login-container">
            <div class="login">{{ request.user.username }}</div>
            <div class="menu"><a class="change-password" href="/admin/password_change/" target="_blank">Изменить пароль</a></div>
        </div>
        <nav class="nav">
            <a href="" class="reset-link">Сброс</a>
            <button class="button" type="submit" form="form">Сохранить</button>
            <a href="/admin/reconciliation_app/reconciliationdate/" class="nav-btn" target="_blank">Даты сверок</a>
            <a href="{% url 'rc_app:logout_view' %}" class="nav-btn">Выход</a>
        </nav>
    </header>
    <main class="main" id="main">
        <form class="form" action="" method="post" id="form">
            {% csrf_token %}
            {% for c in categories %}
            <div class="one-category">
                <h1 class="category-title">{{ c.name }}</h1>
                <div class="products">
                    {% for p in c.product_set.all %}
                    <div class="one-product">
                        <label class="label" for="{{ p.id }}">{{ p.name }}</label>
                        <input class="input" id="{{ p.id }}" type="date" name="{{ p.id }}" value="{% get_latest p.id %}" onchange="(this.parentNode.classList.add('changed')); (document.querySelector('.button').classList.add('active')); (document.querySelector('.reset-link').classList.add('active'))">
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </form>
    </main>
    <footer class="footer">
        <a class="up" href="#main"><p class="up-text">Вверх</p></a>
    </footer>
    {% block js %}
    <script type="module" src="{% static 'reconciliation_app/js/script.js' %}"></script>
    {% endblock js %}
</div>
{% endblock content %}